### ISSUE TITLE
Question: What types of coffee beans are in the dataset?

### ISSUE THREAD

**Issue by septian-dika** [Tauranis/deep_coffee#6]
Hello, I am a student at one of the universities.
I tried to find your contact before but couldn't find it. So I asked permission, and asked here.
I want to use the image dataset you provided, but what types of coffee beans are in the dataset ?. I think the coffee beans are 'Robusta', but I need an official claim from you.
So I need your image dataset, for the implementation of coffee bean image detection into the android application (only for research). I will also include your citation to my research.

**Comment by Tauranis** [comment]
Hi @septian-dika , Thanks for the contact.
Feel free to use the dataset at your will.
The coffee specie is "Coffea arabica" from a small farmer at the city of Bueno Brandão - MG - Brazil. (https://www.google.com.br/maps/place/22%C2%B024'42.0%22S+46%C2%B021'25.0%22W/)

**Comment by Tauranis** [comment]
For more info, please read here
https://medium.com/swlh/automation-for-coffee-bean-selection-79a6b32b88de
